import React, { useLayoutEffect } from "react";
import { SafeAreaView, View, Text, TouchableOpacity, StyleSheet, ScrollView } from "react-native";
import { Feather } from "@expo/vector-icons";
import { useNavigation } from "expo-router";

export default function TermsScreen() {
  const navigation = useNavigation();

  // Remove the default navigation header
  useLayoutEffect(() => {
    navigation.setOptions({
      headerShown: false,
    });
  }, [navigation]);

  return (
    <SafeAreaView style={styles.container}>
      <View className="flex-row items-center px-5 pt-4 pb-2" style={{ alignItems: "center" }}>
        <TouchableOpacity onPress={() => navigation.goBack()} className="p-1">
          <Feather name="x" size={24} color="#111827" />
        </TouchableOpacity>
        <View style={{ width: 28 }} />
      </View>
      <ScrollView style={styles.content} contentContainerStyle={styles.contentContainer}>
        <Text style={styles.sectionTitle}>Terms and Conditions for TALKAI</Text>
        <Text style={styles.date}>Last Updated: September 26, 2025</Text>
        <Text style={styles.paragraph}>
          Welcome to TALKAI (version 2.1.0), an application developed by TALKAI Inc. ("we," "us," or "our"). These Terms and Conditions ("Terms") govern your access to and use of the TALKAI mobile application ("App"), including its features such as the chatbot, document summarization, real-time audio conversation, access to uploaded documents, AI humanization, and scan-to-solve question functionality. By downloading, installing, accessing, or using the App, you agree to be bound by these Terms. If you do not agree with these Terms, you must not use the App.
        </Text>

        <Text style={styles.subTitle}>1. Acceptance of Terms</Text>
        <Text style={styles.paragraph}>
          By using TALKAI, you confirm that you are at least 18 years old or have the consent of a parent or legal guardian, and you agree to comply with these Terms. We reserve the right to update or modify these Terms at any time, and such changes will be effective immediately upon posting within the App or on our website. Your continued use of the App after any changes constitutes your acceptance of the updated Terms.
        </Text>

        <Text style={styles.subTitle}>2. Description of Services</Text>
        <Text style={styles.paragraph}>
          TALKAI provides the following features:
        </Text>
        <Text style={styles.listItem}>● Chatbot: Engage in text-based conversations with an AI-powered chatbot for assistance, information, or entertainment.</Text>
        <Text style={styles.listItem}>● Document Summarization: Upload documents to receive concise summaries generated by our AI.</Text>
        <Text style={styles.listItem}>● Real-Time Audio Conversation: Interact with the AI through voice-based conversations in real time.</Text>
        <Text style={styles.listItem}>● Access to Uploaded Documents: The AI can access and reference documents you upload to provide relevant responses or insights.</Text>
        <Text style={styles.listItem}>● AI Humanization: Convert AI-generated text into a more natural, human-like tone.</Text>
        <Text style={styles.listItem}>● Scan-to-Solve: Scan questions or problems to receive AI-generated solutions or explanations.</Text>
        <Text style={styles.paragraph}>
          We may update, modify, or discontinue any feature at our discretion without prior notice.
        </Text>

        <Text style={styles.subTitle}>3. User Responsibilities</Text>
        <Text style={styles.subSubTitle}>3.1. Account Creation and Security</Text>
        <Text style={styles.listItem}>● You may need to create an account to access certain features of the App. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.</Text>
        <Text style={styles.listItem}>● You agree to notify us immediately of any unauthorized use of your account or any other breach of security.</Text>

        <Text style={styles.subSubTitle}>3.2. Acceptable Use</Text>
        <Text style={styles.paragraph}>
          You agree to use TALKAI only for lawful purposes and in accordance with these Terms. You shall not:
        </Text>
        <Text style={styles.listItem}>● Use the App to upload, share, or transmit content that is illegal, harmful, defamatory, obscene, or otherwise objectionable.</Text>
        <Text style={styles.listItem}>● Attempt to reverse-engineer, decompile, or hack the App or its features.</Text>
        <Text style={styles.listItem}>● Use the App to infringe on the intellectual property rights of others.</Text>
        <Text style={styles.listItem}>● Overload, disrupt, or interfere with the App’s servers or networks.</Text>

        <Text style={styles.subSubTitle}>3.3. Uploaded Content</Text>
        <Text style={styles.listItem}>● You retain ownership of any documents or content you upload to the App ("User Content"). By uploading User Content, you grant us a non-exclusive, worldwide, royalty-free license to use, store, process, and analyze your User Content solely for the purpose of providing and improving the App’s services.</Text>
        <Text style={styles.listItem}>● You are responsible for ensuring that your User Content does not violate any laws or third-party rights.</Text>

        <Text style={styles.subTitle}>4. Intellectual Property</Text>
        <Text style={styles.listItem}>● Ownership: All content, features, and functionality of TALKAI, including but not limited to the chatbot, AI algorithms, and user interface, are owned by TALKAI Inc. or its licensors and are protected by copyright, trademark, and other intellectual property laws.</Text>
        <Text style={styles.listItem}>● Limited License: We grant you a non-exclusive, non-transferable, revocable license to use the App for personal, non-commercial purposes, subject to these Terms.</Text>
        <Text style={styles.listItem}>● Restrictions: You may not copy, modify, distribute, sell, or lease any part of the App without our prior written consent.</Text>

        <Text style={styles.subTitle}>5. Privacy</Text>
        <Text style={styles.paragraph}>
          Your use of TALKAI is also governed by our Privacy Policy, which describes how we collect, use, and protect your personal information. By using the App, you consent to our data practices as outlined in the Privacy Policy.
        </Text>

        <Text style={styles.subTitle}>6. Third-Party Services</Text>
        <Text style={styles.paragraph}>
          TALKAI may integrate with or link to third-party services, such as cloud storage providers or payment processors. We are not responsible for the content, functionality, or policies of these third-party services. Your use of such services is subject to their respective terms and conditions.
        </Text>

        <Text style={styles.subTitle}>7. Disclaimers and Limitation of Liability</Text>
        <Text style={styles.subSubTitle}>7.1. Disclaimers</Text>
        <Text style={styles.listItem}>● TALKAI is provided "as is" and "as available" without warranties of any kind, whether express or implied, including but not limited to warranties of merchantability, fitness for a particular purpose, or non-infringement.</Text>
        <Text style={styles.listItem}>● We do not guarantee the accuracy, reliability, or completeness of the AI-generated responses, summaries, or solutions provided by the App.</Text>
        <Text style={styles.listItem}>● The scan-to-solve feature is intended for educational purposes only and should not be relied upon for professional or critical decision-making.</Text>

        <Text style={styles.subSubTitle}>7.2. Limitation of Liability</Text>
        <Text style={styles.paragraph}>
          To the fullest extent permitted by law, TALKAI Inc. and its affiliates, officers, directors, employees, or agents shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or goodwill, arising from your use of the App. Our total liability for any claim arising from these Terms or your use of the App shall not exceed $100.
        </Text>

        <Text style={styles.subTitle}>8. Termination</Text>
        <Text style={styles.paragraph}>
          We reserve the right to suspend or terminate your access to TALKAI at our sole discretion, with or without notice, for any reason, including if we believe you have violated these Terms. Upon termination, your license to use the App will cease, and you must delete all copies of the App in your possession.
        </Text>

        <Text style={styles.subTitle}>9. Governing Law and Dispute Resolution</Text>
        <Text style={styles.paragraph}>
          These Terms shall be governed by and construed in accordance with the laws of the State of Delaware, USA, without regard to its conflict of law principles. Any disputes arising from these Terms or your use of TALKAI shall be resolved through binding arbitration in Delaware, USA, in accordance with the rules of the American Arbitration Association. You agree to waive any right to participate in a class action lawsuit or class-wide arbitration.
        </Text>

        <Text style={styles.subTitle}>10. Indemnification</Text>
        <Text style={styles.paragraph}>
          You agree to indemnify and hold harmless TALKAI Inc., its affiliates, and their respective officers, directors, employees, and agents from any claims, liabilities, damages, or expenses (including reasonable attorneys’ fees) arising from your use of the App, your User Content, or your violation of these Terms.
        </Text>

        <Text style={styles.subTitle}>11. Miscellaneous</Text>
        <Text style={styles.listItem}>● Entire Agreement: These Terms, together with the Privacy Policy, constitute the entire agreement between you and TALKAI Inc. regarding your use of the App.</Text>
        <Text style={styles.listItem}>● Severability: If any provision of these Terms is found to be invalid or unenforceable, the remaining provisions shall remain in full force and effect.</Text>
        <Text style={styles.listItem}>● Waiver: Our failure to enforce any right or provision of these Terms shall not constitute a waiver of such right or provision.</Text>
        <Text style={styles.listItem}>● Assignment: You may not assign or transfer your rights or obligations under these Terms without our prior written consent. We may assign these Terms without restriction.</Text>

        <Text style={styles.subTitle}>12. Contact Us</Text>
        <Text style={styles.paragraph}>
          If you have any questions or concerns about these Terms, please contact us at:
        </Text>
        <Text style={styles.paragraph}>
          <Text style={styles.bold}>TALKAI Inc.</Text>
        </Text>
        <Text style={styles.paragraph}>
          Email: support@talkai.com
        </Text>
        <Text style={styles.paragraph}>
          Address: 123 Innovation Drive, Suite 100, Wilmington, DE 19801, USA
        </Text>
        <Text style={styles.paragraph}>
          By using TALKAI, you acknowledge that you have read, understood, and agree to be bound by these Terms and Conditions.
        </Text>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F9FAFB",
    paddingTop: 30,
  },
  content: {
    paddingHorizontal: 24,
  },
  contentContainer: {
    paddingBottom: 60, // Increased bottom padding to avoid content being too close to the bottom
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#111827",
  },
  sectionTitle: {
    fontSize: 20,
    color: "#1F2937",
    fontWeight: "700",
    marginBottom: 12,
  },
  date: {
    fontSize: 14,
    color: "#4B5563",
    marginBottom: 20,
    fontWeight: "500",
  },
  subTitle: {
    fontSize: 18,
    color: "#1F2937",
    fontWeight: "600",
    marginTop: 20,
    marginBottom: 12,
  },
  subSubTitle: {
    fontSize: 16,
    color: "#1F2937",
    fontWeight: "600",
    marginTop: 16,
    marginBottom: 10,
  },
  paragraph: {
    fontSize: 15,
    color: "#374151",
    marginBottom: 16,
    lineHeight: 24,
  },
  listItem: {
    fontSize: 15,
    color: "#374151",
    marginBottom: 12,
    marginLeft: 12,
    lineHeight: 24,
  },
  bold: {
    fontWeight: "700",
  },
});